### ISSUE TITLE
Create a contract to issue NFT achievement badges for HackerLink Hackers

### ISSUE THREAD

**Issue by zhangjiannan** [dorahacksglobal/hackerlinkbounties#1]
Create an open-source Ethereum/BSC contract to issue NFT achievement badges for HackerLink Hackers

Example badges include:
- Hackathon Winner
- Grant Receiver
- Bounty Solver

Write the contract, test the contract, and well document the contract so that we can well integrate it into our product.

Bounty price: 1ETH.

**Comment by tari404** [comment]
viewing code
